// Code generated by smithy-swift-codegen. DO NOT EDIT!

import ClientRuntime

/// Amazon Cloud Directory Amazon Cloud Directory is a component of the AWS Directory Service that simplifies the development and management of cloud-scale web, mobile, and IoT applications. This guide describes the Cloud Directory operations that you can call programmatically and includes detailed information on data types and errors. For information about Cloud Directory features, see [AWS Directory Service](https://aws.amazon.com/directoryservice/) and the [Amazon Cloud Directory Developer Guide](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/what_is_cloud_directory.html).
public protocol CloudDirectoryClientProtocol {
    /// Performs the `AddFacetToObject` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Adds a new [Facet] to an object. An object can have more than one facet applied on it.
    ///
    /// - Parameter AddFacetToObjectInput : [no documentation found]
    ///
    /// - Returns: `AddFacetToObjectOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `DirectoryNotEnabledException` : Operations are only permitted on enabled directories.
    /// - `FacetValidationException` : The [Facet] that you provided was not well formed or could not be validated with the schema.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func addFacetToObject(input: AddFacetToObjectInput) async throws -> AddFacetToObjectOutput
    /// Performs the `ApplySchema` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Copies the input published schema, at the specified version, into the [Directory] with the same name and version as that of the published schema.
    ///
    /// - Parameter ApplySchemaInput : [no documentation found]
    ///
    /// - Returns: `ApplySchemaOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `InvalidAttachmentException` : Indicates that an attempt to make an attachment was invalid. For example, attaching two nodes with a link type that is not applicable to the nodes or attempting to apply a schema to a directory a second time.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `SchemaAlreadyExistsException` : Indicates that a schema could not be created due to a naming conflict. Please select a different name and then try again.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func applySchema(input: ApplySchemaInput) async throws -> ApplySchemaOutput
    /// Performs the `AttachObject` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Attaches an existing object to another object. An object can be accessed in two ways:
    ///
    /// * Using the path
    ///
    /// * Using ObjectIdentifier
    ///
    /// - Parameter AttachObjectInput : [no documentation found]
    ///
    /// - Returns: `AttachObjectOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `DirectoryNotEnabledException` : Operations are only permitted on enabled directories.
    /// - `FacetValidationException` : The [Facet] that you provided was not well formed or could not be validated with the schema.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `InvalidAttachmentException` : Indicates that an attempt to make an attachment was invalid. For example, attaching two nodes with a link type that is not applicable to the nodes or attempting to apply a schema to a directory a second time.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `LinkNameAlreadyInUseException` : Indicates that a link could not be created due to a naming conflict. Choose a different name and then try again.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func attachObject(input: AttachObjectInput) async throws -> AttachObjectOutput
    /// Performs the `AttachPolicy` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Attaches a policy object to a regular object. An object can have a limited number of attached policies.
    ///
    /// - Parameter AttachPolicyInput : [no documentation found]
    ///
    /// - Returns: `AttachPolicyOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `DirectoryNotEnabledException` : Operations are only permitted on enabled directories.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `NotPolicyException` : Indicates that the requested operation can only operate on policy objects.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func attachPolicy(input: AttachPolicyInput) async throws -> AttachPolicyOutput
    /// Performs the `AttachToIndex` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Attaches the specified object to the specified index.
    ///
    /// - Parameter AttachToIndexInput : [no documentation found]
    ///
    /// - Returns: `AttachToIndexOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `DirectoryNotEnabledException` : Operations are only permitted on enabled directories.
    /// - `IndexedAttributeMissingException` : An object has been attempted to be attached to an object that does not have the appropriate attribute value.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `InvalidAttachmentException` : Indicates that an attempt to make an attachment was invalid. For example, attaching two nodes with a link type that is not applicable to the nodes or attempting to apply a schema to a directory a second time.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `LinkNameAlreadyInUseException` : Indicates that a link could not be created due to a naming conflict. Choose a different name and then try again.
    /// - `NotIndexException` : Indicates that the requested operation can only operate on index objects.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func attachToIndex(input: AttachToIndexInput) async throws -> AttachToIndexOutput
    /// Performs the `AttachTypedLink` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Attaches a typed link to a specified source and target object. For more information, see [Typed Links](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/directory_objects_links.html#directory_objects_links_typedlink).
    ///
    /// - Parameter AttachTypedLinkInput : [no documentation found]
    ///
    /// - Returns: `AttachTypedLinkOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `DirectoryNotEnabledException` : Operations are only permitted on enabled directories.
    /// - `FacetValidationException` : The [Facet] that you provided was not well formed or could not be validated with the schema.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `InvalidAttachmentException` : Indicates that an attempt to make an attachment was invalid. For example, attaching two nodes with a link type that is not applicable to the nodes or attempting to apply a schema to a directory a second time.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func attachTypedLink(input: AttachTypedLinkInput) async throws -> AttachTypedLinkOutput
    /// Performs the `BatchRead` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Performs all the read operations in a batch.
    ///
    /// - Parameter BatchReadInput : [no documentation found]
    ///
    /// - Returns: `BatchReadOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `DirectoryNotEnabledException` : Operations are only permitted on enabled directories.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func batchRead(input: BatchReadInput) async throws -> BatchReadOutput
    /// Performs the `BatchWrite` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Performs all the write operations in a batch. Either all the operations succeed or none.
    ///
    /// - Parameter BatchWriteInput : [no documentation found]
    ///
    /// - Returns: `BatchWriteOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `BatchWriteException` : A BatchWrite exception has occurred.
    /// - `DirectoryNotEnabledException` : Operations are only permitted on enabled directories.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func batchWrite(input: BatchWriteInput) async throws -> BatchWriteOutput
    /// Performs the `CreateDirectory` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Creates a [Directory] by copying the published schema into the directory. A directory cannot be created without a schema. You can also quickly create a directory using a managed schema, called the QuickStartSchema. For more information, see [Managed Schema](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/schemas_managed.html) in the Amazon Cloud Directory Developer Guide.
    ///
    /// - Parameter CreateDirectoryInput : [no documentation found]
    ///
    /// - Returns: `CreateDirectoryOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `DirectoryAlreadyExistsException` : Indicates that a [Directory] could not be created due to a naming conflict. Choose a different name and try again.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func createDirectory(input: CreateDirectoryInput) async throws -> CreateDirectoryOutput
    /// Performs the `CreateFacet` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Creates a new [Facet] in a schema. Facet creation is allowed only in development or applied schemas.
    ///
    /// - Parameter CreateFacetInput : [no documentation found]
    ///
    /// - Returns: `CreateFacetOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `FacetAlreadyExistsException` : A facet with the same name already exists.
    /// - `FacetValidationException` : The [Facet] that you provided was not well formed or could not be validated with the schema.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `InvalidRuleException` : Occurs when any of the rule parameter keys or values are invalid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func createFacet(input: CreateFacetInput) async throws -> CreateFacetOutput
    /// Performs the `CreateIndex` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Creates an index object. See [Indexing and search](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/indexing_search.html) for more information.
    ///
    /// - Parameter CreateIndexInput : [no documentation found]
    ///
    /// - Returns: `CreateIndexOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `DirectoryNotEnabledException` : Operations are only permitted on enabled directories.
    /// - `FacetValidationException` : The [Facet] that you provided was not well formed or could not be validated with the schema.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `LinkNameAlreadyInUseException` : Indicates that a link could not be created due to a naming conflict. Choose a different name and then try again.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `UnsupportedIndexTypeException` : Indicates that the requested index type is not supported.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func createIndex(input: CreateIndexInput) async throws -> CreateIndexOutput
    /// Performs the `CreateObject` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Creates an object in a [Directory]. Additionally attaches the object to a parent, if a parent reference and LinkName is specified. An object is simply a collection of [Facet] attributes. You can also use this API call to create a policy object, if the facet from which you create the object is a policy facet.
    ///
    /// - Parameter CreateObjectInput : [no documentation found]
    ///
    /// - Returns: `CreateObjectOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `DirectoryNotEnabledException` : Operations are only permitted on enabled directories.
    /// - `FacetValidationException` : The [Facet] that you provided was not well formed or could not be validated with the schema.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `LinkNameAlreadyInUseException` : Indicates that a link could not be created due to a naming conflict. Choose a different name and then try again.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `UnsupportedIndexTypeException` : Indicates that the requested index type is not supported.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func createObject(input: CreateObjectInput) async throws -> CreateObjectOutput
    /// Performs the `CreateSchema` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Creates a new schema in a development state. A schema can exist in three phases:
    ///
    /// * Development: This is a mutable phase of the schema. All new schemas are in the development phase. Once the schema is finalized, it can be published.
    ///
    /// * Published: Published schemas are immutable and have a version associated with them.
    ///
    /// * Applied: Applied schemas are mutable in a way that allows you to add new schema facets. You can also add new, nonrequired attributes to existing schema facets. You can apply only published schemas to directories.
    ///
    /// - Parameter CreateSchemaInput : [no documentation found]
    ///
    /// - Returns: `CreateSchemaOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `SchemaAlreadyExistsException` : Indicates that a schema could not be created due to a naming conflict. Please select a different name and then try again.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func createSchema(input: CreateSchemaInput) async throws -> CreateSchemaOutput
    /// Performs the `CreateTypedLinkFacet` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Creates a [TypedLinkFacet]. For more information, see [Typed Links](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/directory_objects_links.html#directory_objects_links_typedlink).
    ///
    /// - Parameter CreateTypedLinkFacetInput : [no documentation found]
    ///
    /// - Returns: `CreateTypedLinkFacetOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `FacetAlreadyExistsException` : A facet with the same name already exists.
    /// - `FacetValidationException` : The [Facet] that you provided was not well formed or could not be validated with the schema.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `InvalidRuleException` : Occurs when any of the rule parameter keys or values are invalid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func createTypedLinkFacet(input: CreateTypedLinkFacetInput) async throws -> CreateTypedLinkFacetOutput
    /// Performs the `DeleteDirectory` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Deletes a directory. Only disabled directories can be deleted. A deleted directory cannot be undone. Exercise extreme caution when deleting directories.
    ///
    /// - Parameter DeleteDirectoryInput : [no documentation found]
    ///
    /// - Returns: `DeleteDirectoryOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `DirectoryDeletedException` : A directory that has been deleted and to which access has been attempted. Note: The requested resource will eventually cease to exist.
    /// - `DirectoryNotDisabledException` : An operation can only operate on a disabled directory.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func deleteDirectory(input: DeleteDirectoryInput) async throws -> DeleteDirectoryOutput
    /// Performs the `DeleteFacet` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Deletes a given [Facet]. All attributes and [Rule]s that are associated with the facet will be deleted. Only development schema facets are allowed deletion.
    ///
    /// - Parameter DeleteFacetInput : [no documentation found]
    ///
    /// - Returns: `DeleteFacetOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `FacetInUseException` : Occurs when deleting a facet that contains an attribute that is a target to an attribute reference in a different facet.
    /// - `FacetNotFoundException` : The specified [Facet] could not be found.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func deleteFacet(input: DeleteFacetInput) async throws -> DeleteFacetOutput
    /// Performs the `DeleteObject` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Deletes an object and its associated attributes. Only objects with no children and no parents can be deleted. The maximum number of attributes that can be deleted during an object deletion is 30. For more information, see [Amazon Cloud Directory Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html).
    ///
    /// - Parameter DeleteObjectInput : [no documentation found]
    ///
    /// - Returns: `DeleteObjectOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `DirectoryNotEnabledException` : Operations are only permitted on enabled directories.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ObjectNotDetachedException` : Indicates that the requested operation cannot be completed because the object has not been detached from the tree.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func deleteObject(input: DeleteObjectInput) async throws -> DeleteObjectOutput
    /// Performs the `DeleteSchema` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Deletes a given schema. Schemas in a development and published state can only be deleted.
    ///
    /// - Parameter DeleteSchemaInput : [no documentation found]
    ///
    /// - Returns: `DeleteSchemaOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `StillContainsLinksException` : The object could not be deleted because links still exist. Remove the links and then try the operation again.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func deleteSchema(input: DeleteSchemaInput) async throws -> DeleteSchemaOutput
    /// Performs the `DeleteTypedLinkFacet` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Deletes a [TypedLinkFacet]. For more information, see [Typed Links](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/directory_objects_links.html#directory_objects_links_typedlink).
    ///
    /// - Parameter DeleteTypedLinkFacetInput : [no documentation found]
    ///
    /// - Returns: `DeleteTypedLinkFacetOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `FacetNotFoundException` : The specified [Facet] could not be found.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func deleteTypedLinkFacet(input: DeleteTypedLinkFacetInput) async throws -> DeleteTypedLinkFacetOutput
    /// Performs the `DetachFromIndex` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Detaches the specified object from the specified index.
    ///
    /// - Parameter DetachFromIndexInput : [no documentation found]
    ///
    /// - Returns: `DetachFromIndexOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `DirectoryNotEnabledException` : Operations are only permitted on enabled directories.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `NotIndexException` : Indicates that the requested operation can only operate on index objects.
    /// - `ObjectAlreadyDetachedException` : Indicates that the object is not attached to the index.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func detachFromIndex(input: DetachFromIndexInput) async throws -> DetachFromIndexOutput
    /// Performs the `DetachObject` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Detaches a given object from the parent object. The object that is to be detached from the parent is specified by the link name.
    ///
    /// - Parameter DetachObjectInput : [no documentation found]
    ///
    /// - Returns: `DetachObjectOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `DirectoryNotEnabledException` : Operations are only permitted on enabled directories.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `NotNodeException` : Occurs when any invalid operations are performed on an object that is not a node, such as calling ListObjectChildren for a leaf node object.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func detachObject(input: DetachObjectInput) async throws -> DetachObjectOutput
    /// Performs the `DetachPolicy` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Detaches a policy from an object.
    ///
    /// - Parameter DetachPolicyInput : [no documentation found]
    ///
    /// - Returns: `DetachPolicyOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `DirectoryNotEnabledException` : Operations are only permitted on enabled directories.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `NotPolicyException` : Indicates that the requested operation can only operate on policy objects.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func detachPolicy(input: DetachPolicyInput) async throws -> DetachPolicyOutput
    /// Performs the `DetachTypedLink` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Detaches a typed link from a specified source and target object. For more information, see [Typed Links](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/directory_objects_links.html#directory_objects_links_typedlink).
    ///
    /// - Parameter DetachTypedLinkInput : [no documentation found]
    ///
    /// - Returns: `DetachTypedLinkOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `DirectoryNotEnabledException` : Operations are only permitted on enabled directories.
    /// - `FacetValidationException` : The [Facet] that you provided was not well formed or could not be validated with the schema.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func detachTypedLink(input: DetachTypedLinkInput) async throws -> DetachTypedLinkOutput
    /// Performs the `DisableDirectory` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Disables the specified directory. Disabled directories cannot be read or written to. Only enabled directories can be disabled. Disabled directories may be reenabled.
    ///
    /// - Parameter DisableDirectoryInput : [no documentation found]
    ///
    /// - Returns: `DisableDirectoryOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `DirectoryDeletedException` : A directory that has been deleted and to which access has been attempted. Note: The requested resource will eventually cease to exist.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func disableDirectory(input: DisableDirectoryInput) async throws -> DisableDirectoryOutput
    /// Performs the `EnableDirectory` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Enables the specified directory. Only disabled directories can be enabled. Once enabled, the directory can then be read and written to.
    ///
    /// - Parameter EnableDirectoryInput : [no documentation found]
    ///
    /// - Returns: `EnableDirectoryOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `DirectoryDeletedException` : A directory that has been deleted and to which access has been attempted. Note: The requested resource will eventually cease to exist.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func enableDirectory(input: EnableDirectoryInput) async throws -> EnableDirectoryOutput
    /// Performs the `GetAppliedSchemaVersion` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Returns current applied schema version ARN, including the minor version in use.
    ///
    /// - Parameter GetAppliedSchemaVersionInput : [no documentation found]
    ///
    /// - Returns: `GetAppliedSchemaVersionOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func getAppliedSchemaVersion(input: GetAppliedSchemaVersionInput) async throws -> GetAppliedSchemaVersionOutput
    /// Performs the `GetDirectory` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Retrieves metadata about a directory.
    ///
    /// - Parameter GetDirectoryInput : [no documentation found]
    ///
    /// - Returns: `GetDirectoryOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func getDirectory(input: GetDirectoryInput) async throws -> GetDirectoryOutput
    /// Performs the `GetFacet` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Gets details of the [Facet], such as facet name, attributes, [Rule]s, or ObjectType. You can call this on all kinds of schema facets -- published, development, or applied.
    ///
    /// - Parameter GetFacetInput : [no documentation found]
    ///
    /// - Returns: `GetFacetOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `FacetNotFoundException` : The specified [Facet] could not be found.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func getFacet(input: GetFacetInput) async throws -> GetFacetOutput
    /// Performs the `GetLinkAttributes` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Retrieves attributes that are associated with a typed link.
    ///
    /// - Parameter GetLinkAttributesInput : [no documentation found]
    ///
    /// - Returns: `GetLinkAttributesOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `DirectoryNotEnabledException` : Operations are only permitted on enabled directories.
    /// - `FacetValidationException` : The [Facet] that you provided was not well formed or could not be validated with the schema.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func getLinkAttributes(input: GetLinkAttributesInput) async throws -> GetLinkAttributesOutput
    /// Performs the `GetObjectAttributes` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Retrieves attributes within a facet that are associated with an object.
    ///
    /// - Parameter GetObjectAttributesInput : [no documentation found]
    ///
    /// - Returns: `GetObjectAttributesOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `DirectoryNotEnabledException` : Operations are only permitted on enabled directories.
    /// - `FacetValidationException` : The [Facet] that you provided was not well formed or could not be validated with the schema.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func getObjectAttributes(input: GetObjectAttributesInput) async throws -> GetObjectAttributesOutput
    /// Performs the `GetObjectInformation` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Retrieves metadata about an object.
    ///
    /// - Parameter GetObjectInformationInput : [no documentation found]
    ///
    /// - Returns: `GetObjectInformationOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `DirectoryNotEnabledException` : Operations are only permitted on enabled directories.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func getObjectInformation(input: GetObjectInformationInput) async throws -> GetObjectInformationOutput
    /// Performs the `GetSchemaAsJson` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Retrieves a JSON representation of the schema. See [JSON Schema Format](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/schemas_jsonformat.html#schemas_json) for more information.
    ///
    /// - Parameter GetSchemaAsJsonInput : [no documentation found]
    ///
    /// - Returns: `GetSchemaAsJsonOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func getSchemaAsJson(input: GetSchemaAsJsonInput) async throws -> GetSchemaAsJsonOutput
    /// Performs the `GetTypedLinkFacetInformation` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Returns the identity attribute order for a specific [TypedLinkFacet]. For more information, see [Typed Links](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/directory_objects_links.html#directory_objects_links_typedlink).
    ///
    /// - Parameter GetTypedLinkFacetInformationInput : [no documentation found]
    ///
    /// - Returns: `GetTypedLinkFacetInformationOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `FacetNotFoundException` : The specified [Facet] could not be found.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `InvalidNextTokenException` : Indicates that the NextToken value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func getTypedLinkFacetInformation(input: GetTypedLinkFacetInformationInput) async throws -> GetTypedLinkFacetInformationOutput
    /// Performs the `ListAppliedSchemaArns` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Lists schema major versions applied to a directory. If SchemaArn is provided, lists the minor version.
    ///
    /// - Parameter ListAppliedSchemaArnsInput : [no documentation found]
    ///
    /// - Returns: `ListAppliedSchemaArnsOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `InvalidNextTokenException` : Indicates that the NextToken value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func listAppliedSchemaArns(input: ListAppliedSchemaArnsInput) async throws -> ListAppliedSchemaArnsOutput
    /// Performs the `ListAttachedIndices` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Lists indices attached to the specified object.
    ///
    /// - Parameter ListAttachedIndicesInput : [no documentation found]
    ///
    /// - Returns: `ListAttachedIndicesOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `DirectoryNotEnabledException` : Operations are only permitted on enabled directories.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func listAttachedIndices(input: ListAttachedIndicesInput) async throws -> ListAttachedIndicesOutput
    /// Performs the `ListDevelopmentSchemaArns` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Retrieves each Amazon Resource Name (ARN) of schemas in the development state.
    ///
    /// - Parameter ListDevelopmentSchemaArnsInput : [no documentation found]
    ///
    /// - Returns: `ListDevelopmentSchemaArnsOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `InvalidNextTokenException` : Indicates that the NextToken value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func listDevelopmentSchemaArns(input: ListDevelopmentSchemaArnsInput) async throws -> ListDevelopmentSchemaArnsOutput
    /// Performs the `ListDirectories` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Lists directories created within an account.
    ///
    /// - Parameter ListDirectoriesInput : [no documentation found]
    ///
    /// - Returns: `ListDirectoriesOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `InvalidNextTokenException` : Indicates that the NextToken value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func listDirectories(input: ListDirectoriesInput) async throws -> ListDirectoriesOutput
    /// Performs the `ListFacetAttributes` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Retrieves attributes attached to the facet.
    ///
    /// - Parameter ListFacetAttributesInput : [no documentation found]
    ///
    /// - Returns: `ListFacetAttributesOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `FacetNotFoundException` : The specified [Facet] could not be found.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `InvalidNextTokenException` : Indicates that the NextToken value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func listFacetAttributes(input: ListFacetAttributesInput) async throws -> ListFacetAttributesOutput
    /// Performs the `ListFacetNames` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Retrieves the names of facets that exist in a schema.
    ///
    /// - Parameter ListFacetNamesInput : [no documentation found]
    ///
    /// - Returns: `ListFacetNamesOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `InvalidNextTokenException` : Indicates that the NextToken value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func listFacetNames(input: ListFacetNamesInput) async throws -> ListFacetNamesOutput
    /// Performs the `ListIncomingTypedLinks` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Returns a paginated list of all the incoming [TypedLinkSpecifier] information for an object. It also supports filtering by typed link facet and identity attributes. For more information, see [Typed Links](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/directory_objects_links.html#directory_objects_links_typedlink).
    ///
    /// - Parameter ListIncomingTypedLinksInput : [no documentation found]
    ///
    /// - Returns: `ListIncomingTypedLinksOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `DirectoryNotEnabledException` : Operations are only permitted on enabled directories.
    /// - `FacetValidationException` : The [Facet] that you provided was not well formed or could not be validated with the schema.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `InvalidNextTokenException` : Indicates that the NextToken value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func listIncomingTypedLinks(input: ListIncomingTypedLinksInput) async throws -> ListIncomingTypedLinksOutput
    /// Performs the `ListIndex` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Lists objects attached to the specified index.
    ///
    /// - Parameter ListIndexInput : [no documentation found]
    ///
    /// - Returns: `ListIndexOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `DirectoryNotEnabledException` : Operations are only permitted on enabled directories.
    /// - `FacetValidationException` : The [Facet] that you provided was not well formed or could not be validated with the schema.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `InvalidNextTokenException` : Indicates that the NextToken value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `NotIndexException` : Indicates that the requested operation can only operate on index objects.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func listIndex(input: ListIndexInput) async throws -> ListIndexOutput
    /// Performs the `ListManagedSchemaArns` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Lists the major version families of each managed schema. If a major version ARN is provided as SchemaArn, the minor version revisions in that family are listed instead.
    ///
    /// - Parameter ListManagedSchemaArnsInput : [no documentation found]
    ///
    /// - Returns: `ListManagedSchemaArnsOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `InvalidNextTokenException` : Indicates that the NextToken value is not valid.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func listManagedSchemaArns(input: ListManagedSchemaArnsInput) async throws -> ListManagedSchemaArnsOutput
    /// Performs the `ListObjectAttributes` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Lists all attributes that are associated with an object.
    ///
    /// - Parameter ListObjectAttributesInput : [no documentation found]
    ///
    /// - Returns: `ListObjectAttributesOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `DirectoryNotEnabledException` : Operations are only permitted on enabled directories.
    /// - `FacetValidationException` : The [Facet] that you provided was not well formed or could not be validated with the schema.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `InvalidNextTokenException` : Indicates that the NextToken value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func listObjectAttributes(input: ListObjectAttributesInput) async throws -> ListObjectAttributesOutput
    /// Performs the `ListObjectChildren` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Returns a paginated list of child objects that are associated with a given object.
    ///
    /// - Parameter ListObjectChildrenInput : [no documentation found]
    ///
    /// - Returns: `ListObjectChildrenOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `DirectoryNotEnabledException` : Operations are only permitted on enabled directories.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `InvalidNextTokenException` : Indicates that the NextToken value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `NotNodeException` : Occurs when any invalid operations are performed on an object that is not a node, such as calling ListObjectChildren for a leaf node object.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func listObjectChildren(input: ListObjectChildrenInput) async throws -> ListObjectChildrenOutput
    /// Performs the `ListObjectParentPaths` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Retrieves all available parent paths for any object type such as node, leaf node, policy node, and index node objects. For more information about objects, see [Directory Structure](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/key_concepts_directorystructure.html). Use this API to evaluate all parents for an object. The call returns all objects from the root of the directory up to the requested object. The API returns the number of paths based on user-defined MaxResults, in case there are multiple paths to the parent. The order of the paths and nodes returned is consistent among multiple API calls unless the objects are deleted or moved. Paths not leading to the directory root are ignored from the target object.
    ///
    /// - Parameter ListObjectParentPathsInput : [no documentation found]
    ///
    /// - Returns: `ListObjectParentPathsOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `DirectoryNotEnabledException` : Operations are only permitted on enabled directories.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `InvalidNextTokenException` : Indicates that the NextToken value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func listObjectParentPaths(input: ListObjectParentPathsInput) async throws -> ListObjectParentPathsOutput
    /// Performs the `ListObjectParents` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Lists parent objects that are associated with a given object in pagination fashion.
    ///
    /// - Parameter ListObjectParentsInput : [no documentation found]
    ///
    /// - Returns: `ListObjectParentsOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `CannotListParentOfRootException` : Cannot list the parents of a [Directory] root.
    /// - `DirectoryNotEnabledException` : Operations are only permitted on enabled directories.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `InvalidNextTokenException` : Indicates that the NextToken value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func listObjectParents(input: ListObjectParentsInput) async throws -> ListObjectParentsOutput
    /// Performs the `ListObjectPolicies` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Returns policies attached to an object in pagination fashion.
    ///
    /// - Parameter ListObjectPoliciesInput : [no documentation found]
    ///
    /// - Returns: `ListObjectPoliciesOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `DirectoryNotEnabledException` : Operations are only permitted on enabled directories.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `InvalidNextTokenException` : Indicates that the NextToken value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func listObjectPolicies(input: ListObjectPoliciesInput) async throws -> ListObjectPoliciesOutput
    /// Performs the `ListOutgoingTypedLinks` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Returns a paginated list of all the outgoing [TypedLinkSpecifier] information for an object. It also supports filtering by typed link facet and identity attributes. For more information, see [Typed Links](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/directory_objects_links.html#directory_objects_links_typedlink).
    ///
    /// - Parameter ListOutgoingTypedLinksInput : [no documentation found]
    ///
    /// - Returns: `ListOutgoingTypedLinksOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `DirectoryNotEnabledException` : Operations are only permitted on enabled directories.
    /// - `FacetValidationException` : The [Facet] that you provided was not well formed or could not be validated with the schema.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `InvalidNextTokenException` : Indicates that the NextToken value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func listOutgoingTypedLinks(input: ListOutgoingTypedLinksInput) async throws -> ListOutgoingTypedLinksOutput
    /// Performs the `ListPolicyAttachments` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Returns all of the ObjectIdentifiers to which a given policy is attached.
    ///
    /// - Parameter ListPolicyAttachmentsInput : [no documentation found]
    ///
    /// - Returns: `ListPolicyAttachmentsOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `DirectoryNotEnabledException` : Operations are only permitted on enabled directories.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `InvalidNextTokenException` : Indicates that the NextToken value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `NotPolicyException` : Indicates that the requested operation can only operate on policy objects.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func listPolicyAttachments(input: ListPolicyAttachmentsInput) async throws -> ListPolicyAttachmentsOutput
    /// Performs the `ListPublishedSchemaArns` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Lists the major version families of each published schema. If a major version ARN is provided as SchemaArn, the minor version revisions in that family are listed instead.
    ///
    /// - Parameter ListPublishedSchemaArnsInput : [no documentation found]
    ///
    /// - Returns: `ListPublishedSchemaArnsOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `InvalidNextTokenException` : Indicates that the NextToken value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func listPublishedSchemaArns(input: ListPublishedSchemaArnsInput) async throws -> ListPublishedSchemaArnsOutput
    /// Performs the `ListTagsForResource` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Returns tags for a resource. Tagging is currently supported only for directories with a limit of 50 tags per directory. All 50 tags are returned for a given directory with this API call.
    ///
    /// - Parameter ListTagsForResourceInput : [no documentation found]
    ///
    /// - Returns: `ListTagsForResourceOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `InvalidTaggingRequestException` : Can occur for multiple reasons such as when you tag a resource that doesn’t exist or if you specify a higher number of tags for a resource than the allowed limit. Allowed limit is 50 tags per resource.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func listTagsForResource(input: ListTagsForResourceInput) async throws -> ListTagsForResourceOutput
    /// Performs the `ListTypedLinkFacetAttributes` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Returns a paginated list of all attribute definitions for a particular [TypedLinkFacet]. For more information, see [Typed Links](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/directory_objects_links.html#directory_objects_links_typedlink).
    ///
    /// - Parameter ListTypedLinkFacetAttributesInput : [no documentation found]
    ///
    /// - Returns: `ListTypedLinkFacetAttributesOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `FacetNotFoundException` : The specified [Facet] could not be found.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `InvalidNextTokenException` : Indicates that the NextToken value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func listTypedLinkFacetAttributes(input: ListTypedLinkFacetAttributesInput) async throws -> ListTypedLinkFacetAttributesOutput
    /// Performs the `ListTypedLinkFacetNames` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Returns a paginated list of TypedLink facet names for a particular schema. For more information, see [Typed Links](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/directory_objects_links.html#directory_objects_links_typedlink).
    ///
    /// - Parameter ListTypedLinkFacetNamesInput : [no documentation found]
    ///
    /// - Returns: `ListTypedLinkFacetNamesOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `InvalidNextTokenException` : Indicates that the NextToken value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func listTypedLinkFacetNames(input: ListTypedLinkFacetNamesInput) async throws -> ListTypedLinkFacetNamesOutput
    /// Performs the `LookupPolicy` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Lists all policies from the root of the [Directory] to the object specified. If there are no policies present, an empty list is returned. If policies are present, and if some objects don't have the policies attached, it returns the ObjectIdentifier for such objects. If policies are present, it returns ObjectIdentifier, policyId, and policyType. Paths that don't lead to the root from the target object are ignored. For more information, see [Policies](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/key_concepts_directory.html#key_concepts_policies).
    ///
    /// - Parameter LookupPolicyInput : [no documentation found]
    ///
    /// - Returns: `LookupPolicyOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `DirectoryNotEnabledException` : Operations are only permitted on enabled directories.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `InvalidNextTokenException` : Indicates that the NextToken value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func lookupPolicy(input: LookupPolicyInput) async throws -> LookupPolicyOutput
    /// Performs the `PublishSchema` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Publishes a development schema with a major version and a recommended minor version.
    ///
    /// - Parameter PublishSchemaInput : [no documentation found]
    ///
    /// - Returns: `PublishSchemaOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `SchemaAlreadyPublishedException` : Indicates that a schema is already published.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func publishSchema(input: PublishSchemaInput) async throws -> PublishSchemaOutput
    /// Performs the `PutSchemaFromJson` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Allows a schema to be updated using JSON upload. Only available for development schemas. See [JSON Schema Format](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/schemas_jsonformat.html#schemas_json) for more information.
    ///
    /// - Parameter PutSchemaFromJsonInput : [no documentation found]
    ///
    /// - Returns: `PutSchemaFromJsonOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `InvalidRuleException` : Occurs when any of the rule parameter keys or values are invalid.
    /// - `InvalidSchemaDocException` : Indicates that the provided SchemaDoc value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func putSchemaFromJson(input: PutSchemaFromJsonInput) async throws -> PutSchemaFromJsonOutput
    /// Performs the `RemoveFacetFromObject` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Removes the specified facet from the specified object.
    ///
    /// - Parameter RemoveFacetFromObjectInput : [no documentation found]
    ///
    /// - Returns: `RemoveFacetFromObjectOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `DirectoryNotEnabledException` : Operations are only permitted on enabled directories.
    /// - `FacetValidationException` : The [Facet] that you provided was not well formed or could not be validated with the schema.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func removeFacetFromObject(input: RemoveFacetFromObjectInput) async throws -> RemoveFacetFromObjectOutput
    /// Performs the `TagResource` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// An API operation for adding tags to a resource.
    ///
    /// - Parameter TagResourceInput : [no documentation found]
    ///
    /// - Returns: `TagResourceOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `InvalidTaggingRequestException` : Can occur for multiple reasons such as when you tag a resource that doesn’t exist or if you specify a higher number of tags for a resource than the allowed limit. Allowed limit is 50 tags per resource.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func tagResource(input: TagResourceInput) async throws -> TagResourceOutput
    /// Performs the `UntagResource` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// An API operation for removing tags from a resource.
    ///
    /// - Parameter UntagResourceInput : [no documentation found]
    ///
    /// - Returns: `UntagResourceOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `InvalidTaggingRequestException` : Can occur for multiple reasons such as when you tag a resource that doesn’t exist or if you specify a higher number of tags for a resource than the allowed limit. Allowed limit is 50 tags per resource.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func untagResource(input: UntagResourceInput) async throws -> UntagResourceOutput
    /// Performs the `UpdateFacet` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Does the following:
    ///
    /// * Adds new Attributes, Rules, or ObjectTypes.
    ///
    /// * Updates existing Attributes, Rules, or ObjectTypes.
    ///
    /// * Deletes existing Attributes, Rules, or ObjectTypes.
    ///
    /// - Parameter UpdateFacetInput : [no documentation found]
    ///
    /// - Returns: `UpdateFacetOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `FacetNotFoundException` : The specified [Facet] could not be found.
    /// - `FacetValidationException` : The [Facet] that you provided was not well formed or could not be validated with the schema.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `InvalidFacetUpdateException` : An attempt to modify a [Facet] resulted in an invalid schema exception.
    /// - `InvalidRuleException` : Occurs when any of the rule parameter keys or values are invalid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func updateFacet(input: UpdateFacetInput) async throws -> UpdateFacetOutput
    /// Performs the `UpdateLinkAttributes` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Updates a given typed link’s attributes. Attributes to be updated must not contribute to the typed link’s identity, as defined by its IdentityAttributeOrder.
    ///
    /// - Parameter UpdateLinkAttributesInput : [no documentation found]
    ///
    /// - Returns: `UpdateLinkAttributesOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `DirectoryNotEnabledException` : Operations are only permitted on enabled directories.
    /// - `FacetValidationException` : The [Facet] that you provided was not well formed or could not be validated with the schema.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func updateLinkAttributes(input: UpdateLinkAttributesInput) async throws -> UpdateLinkAttributesOutput
    /// Performs the `UpdateObjectAttributes` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Updates a given object's attributes.
    ///
    /// - Parameter UpdateObjectAttributesInput : [no documentation found]
    ///
    /// - Returns: `UpdateObjectAttributesOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `DirectoryNotEnabledException` : Operations are only permitted on enabled directories.
    /// - `FacetValidationException` : The [Facet] that you provided was not well formed or could not be validated with the schema.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `LinkNameAlreadyInUseException` : Indicates that a link could not be created due to a naming conflict. Choose a different name and then try again.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func updateObjectAttributes(input: UpdateObjectAttributesInput) async throws -> UpdateObjectAttributesOutput
    /// Performs the `UpdateSchema` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Updates the schema name with a new name. Only development schema names can be updated.
    ///
    /// - Parameter UpdateSchemaInput : [no documentation found]
    ///
    /// - Returns: `UpdateSchemaOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func updateSchema(input: UpdateSchemaInput) async throws -> UpdateSchemaOutput
    /// Performs the `UpdateTypedLinkFacet` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Updates a [TypedLinkFacet]. For more information, see [Typed Links](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/directory_objects_links.html#directory_objects_links_typedlink).
    ///
    /// - Parameter UpdateTypedLinkFacetInput : [no documentation found]
    ///
    /// - Returns: `UpdateTypedLinkFacetOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `FacetNotFoundException` : The specified [Facet] could not be found.
    /// - `FacetValidationException` : The [Facet] that you provided was not well formed or could not be validated with the schema.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `InvalidFacetUpdateException` : An attempt to modify a [Facet] resulted in an invalid schema exception.
    /// - `InvalidRuleException` : Occurs when any of the rule parameter keys or values are invalid.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func updateTypedLinkFacet(input: UpdateTypedLinkFacetInput) async throws -> UpdateTypedLinkFacetOutput
    /// Performs the `UpgradeAppliedSchema` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Upgrades a single directory in-place using the PublishedSchemaArn with schema updates found in MinorVersion. Backwards-compatible minor version upgrades are instantaneously available for readers on all objects in the directory. Note: This is a synchronous API call and upgrades only one schema on a given directory per call. To upgrade multiple directories from one schema, you would need to call this API on each directory.
    ///
    /// - Parameter UpgradeAppliedSchemaInput : [no documentation found]
    ///
    /// - Returns: `UpgradeAppliedSchemaOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `IncompatibleSchemaException` : Indicates a failure occurred while performing a check for backward compatibility between the specified schema and the schema that is currently applied to the directory.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `InvalidAttachmentException` : Indicates that an attempt to make an attachment was invalid. For example, attaching two nodes with a link type that is not applicable to the nodes or attempting to apply a schema to a directory a second time.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `SchemaAlreadyExistsException` : Indicates that a schema could not be created due to a naming conflict. Please select a different name and then try again.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func upgradeAppliedSchema(input: UpgradeAppliedSchemaInput) async throws -> UpgradeAppliedSchemaOutput
    /// Performs the `UpgradePublishedSchema` operation on the `AmazonCloudDirectory_20170111` service.
    ///
    /// Upgrades a published schema under a new minor version revision using the current contents of DevelopmentSchemaArn.
    ///
    /// - Parameter UpgradePublishedSchemaInput : [no documentation found]
    ///
    /// - Returns: `UpgradePublishedSchemaOutput` : [no documentation found]
    ///
    /// - Throws: One of the exceptions listed below __Possible Exceptions__.
    ///
    /// __Possible Exceptions:__
    /// - `AccessDeniedException` : Access denied or directory not found. Either you don't have permissions for this directory or the directory does not exist. Try calling [ListDirectories] and check your permissions.
    /// - `IncompatibleSchemaException` : Indicates a failure occurred while performing a check for backward compatibility between the specified schema and the schema that is currently applied to the directory.
    /// - `InternalServiceException` : Indicates a problem that must be resolved by Amazon Web Services. This might be a transient error in which case you can retry your request until it succeeds. Otherwise, go to the [AWS Service Health Dashboard](http://status.aws.amazon.com/) site to see if there are any operational issues with the service.
    /// - `InvalidArnException` : Indicates that the provided ARN value is not valid.
    /// - `InvalidAttachmentException` : Indicates that an attempt to make an attachment was invalid. For example, attaching two nodes with a link type that is not applicable to the nodes or attempting to apply a schema to a directory a second time.
    /// - `LimitExceededException` : Indicates that limits are exceeded. See [Limits](https://docs.aws.amazon.com/clouddirectory/latest/developerguide/limits.html) for more information.
    /// - `ResourceNotFoundException` : The specified resource could not be found.
    /// - `RetryableConflictException` : Occurs when a conflict with a previous successful write is detected. For example, if a write operation occurs on an object and then an attempt is made to read the object using “SERIALIZABLE” consistency, this exception may result. This generally occurs when the previous write did not have time to propagate to the host serving the current request. A retry (with appropriate backoff logic) is the recommended response to this exception.
    /// - `ValidationException` : Indicates that your request is malformed in some manner. See the exception message.
    func upgradePublishedSchema(input: UpgradePublishedSchemaInput) async throws -> UpgradePublishedSchemaOutput
}

public enum CloudDirectoryClientTypes {}
